SOURCES = [
    {"name": "OpenAI News", "url": "https://openai.com/news", "feed_url": "https://openai.com/news/rss.xml", "country": "US", "source_type": "COMPANY"},
    {"name": "Anthropic News", "url": "https://www.anthropic.com/news", "feed_url": "https://www.anthropic.com/news/feed.xml", "country": "US", "source_type": "COMPANY"},
    {"name": "Google DeepMind", "url": "https://deepmind.google/discover/blog/", "feed_url": "https://deepmind.google/blog/rss.xml", "country": "US", "source_type": "COMPANY"},
    {"name": "Google Research", "url": "https://research.google/blog/", "feed_url": "https://research.google/blog/rss/", "country": "US", "source_type": "COMPANY"},
    {"name": "Meta AI", "url": "https://ai.meta.com/blog/", "feed_url": "https://ai.meta.com/blog/rss/", "country": "US", "source_type": "COMPANY"},
    {"name": "Microsoft AI Blog", "url": "https://blogs.microsoft.com/ai/", "feed_url": "https://blogs.microsoft.com/ai/feed/", "country": "US", "source_type": "COMPANY"},
    {"name": "NVIDIA Blog", "url": "https://blogs.nvidia.com/", "feed_url": "https://blogs.nvidia.com/feed/", "country": "US", "source_type": "COMPANY"},
    {"name": "Hugging Face Blog", "url": "https://huggingface.co/blog", "feed_url": "https://huggingface.co/blog/feed.xml", "country": "US", "source_type": "COMPANY"},
    {"name": "BAIR Berkeley AI", "url": "https://bair.berkeley.edu/blog/", "feed_url": "https://bair.berkeley.edu/blog/feed.xml", "country": "US", "source_type": "RESEARCH"},
    {"name": "TechCrunch AI", "url": "https://techcrunch.com/category/artificial-intelligence/", "feed_url": "https://techcrunch.com/category/artificial-intelligence/feed/", "country": "US", "source_type": "NEWS"},
    {"name": "The Verge AI", "url": "https://www.theverge.com/ai-artificial-intelligence", "feed_url": "https://www.theverge.com/ai-artificial-intelligence/rss/index.xml", "country": "US", "source_type": "NEWS"},
    {"name": "MIT Tech Review AI", "url": "https://www.technologyreview.com/topic/artificial-intelligence/", "feed_url": "https://www.technologyreview.com/topic/artificial-intelligence/feed", "country": "US", "source_type": "NEWS"},
    {"name": "Ars Technica AI", "url": "https://arstechnica.com/ai/", "feed_url": "https://arstechnica.com/ai/feed/", "country": "US", "source_type": "NEWS"},
    {"name": "VentureBeat AI", "url": "https://venturebeat.com/category/ai/", "feed_url": "https://venturebeat.com/category/ai/feed/", "country": "US", "source_type": "NEWS"},
    {"name": "South China Morning Post Tech", "url": "https://www.scmp.com/tech", "feed_url": "https://www.scmp.com/rss/36/feed", "country": "CN", "source_type": "NEWS"},
    {"name": "TechNode (China tech)", "url": "https://technode.com/", "feed_url": "https://technode.com/feed/", "country": "CN", "source_type": "NEWS"},
    {"name": "China Daily Tech", "url": "https://www.chinadaily.com.cn/business/tech", "feed_url": "https://www.chinadaily.com.cn/rss/business_rss.xml", "country": "CN", "source_type": "NEWS"},
    {"name": "Caixin Global Tech", "url": "https://www.caixinglobal.com/technology/", "feed_url": "https://www.caixinglobal.com/feed/", "country": "CN", "source_type": "NEWS"},
    {"name": "arXiv cs.AI", "url": "https://arxiv.org/list/cs.AI/recent", "feed_url": "http://export.arxiv.org/rss/cs.AI", "country": "OTHER", "source_type": "RESEARCH"},
    {"name": "arXiv cs.LG", "url": "https://arxiv.org/list/cs.LG/recent", "feed_url": "http://export.arxiv.org/rss/cs.LG", "country": "OTHER", "source_type": "RESEARCH"},
]
