# Generated by Django 6.0.4 on 2026-04-21 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(unique=True)),
                ('feed_url', models.URLField()),
                ('country', models.CharField(choices=[('US', 'United States'), ('CN', 'China'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('source_type', models.CharField(choices=[('COMPANY', 'Company Blog'), ('NEWS', 'News Site'), ('RESEARCH', 'Research')], default='COMPANY', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('published_date', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='newsfeed.source')),
            ],
            options={
                'ordering': ['-published_date'],
                'indexes': [models.Index(fields=['-published_date'], name='newsfeed_ar_publish_f0fbd2_idx'), models.Index(fields=['source', '-published_date'], name='newsfeed_ar_source__71a752_idx')],
            },
        ),
    ]
